rem go-bindata-assetfs static/...
rem go-bindata -o=./web.go   -pkg=web static/...
rem go-bindata   -pkg=web static/...
rem go-bindata-assetfs -pkg web static/...
go-bindata-assetfs -pkg web -o ./assets/web/bindata.go static/...